"""empty message

Revision ID: 28fddfa47cbc
Revises: cbee00e8336d
Create Date: 2021-05-17 17:26:19.995077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fddfa47cbc'
down_revision = 'cbee00e8336d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'debit', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'debit', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
