"""empty message

Revision ID: 47f06790cdee
Revises: e5ffbedeb41d
Create Date: 2021-05-17 18:31:39.729302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f06790cdee'
down_revision = 'e5ffbedeb41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['member_id'], ['id'])
    op.drop_index('member_id', table_name='application')
    op.create_foreign_key(None, 'application', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'debit', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'debit', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_index('member_id', 'application', ['member_id'], unique=True)
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
