"""empty message

Revision ID: 4dda4c44e85b
Revises: 58e7e9c4b09d
Create Date: 2021-05-13 16:44:20.980057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dda4c44e85b'
down_revision = '58e7e9c4b09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['uid'], ['id'])
    op.add_column('member', sa.Column('birthday', sa.String(length=20), nullable=True))
    op.alter_column('member', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.alter_column('member', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('member', 'birthday')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
