"""empty message

Revision ID: 58e7e9c4b09d
Revises: bffce3fc6a71
Create Date: 2021-05-13 15:09:11.338989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e7e9c4b09d'
down_revision = 'bffce3fc6a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['uid'], ['id'])
    op.add_column('member', sa.Column('national_id', sa.String(length=20), nullable=False))
    op.add_column('member', sa.Column('password', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_member_national_id'), 'member', ['national_id'], unique=False)
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_index(op.f('ix_member_national_id'), table_name='member')
    op.drop_column('member', 'password')
    op.drop_column('member', 'national_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
