"""empty message

Revision ID: a47ca0b5271b
Revises: 47f06790cdee
Create Date: 2021-05-18 14:17:25.482707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47ca0b5271b'
down_revision = '47f06790cdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['member_id'], ['id'])
    op.create_index(op.f('ix_application_member_id'), 'application', ['member_id'], unique=False)
    op.create_foreign_key(None, 'application', 'member', ['member_id'], ['id'])
    op.drop_index('ix_debit_number', table_name='debit')
    op.create_index(op.f('ix_debit_number'), 'debit', ['number'], unique=False)
    op.create_foreign_key(None, 'debit', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'debit', type_='foreignkey')
    op.drop_index(op.f('ix_debit_number'), table_name='debit')
    op.create_index('ix_debit_number', 'debit', ['number'], unique=True)
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_index(op.f('ix_application_member_id'), table_name='application')
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
