"""empty message

Revision ID: d8474eb33219
Revises: ebb164abd929
Create Date: 2021-05-17 16:21:32.524843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8474eb33219'
down_revision = 'ebb164abd929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'member', ['member_id'], ['id'])
    op.drop_index('ix_debit_number', table_name='debit')
    op.create_index(op.f('ix_debit_number'), 'debit', ['number'], unique=True)
    op.create_unique_constraint(None, 'debit', ['member_id'])
    op.create_foreign_key(None, 'debit', 'member', ['member_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'debit', type_='foreignkey')
    op.drop_constraint(None, 'debit', type_='unique')
    op.drop_index(op.f('ix_debit_number'), table_name='debit')
    op.create_index('ix_debit_number', 'debit', ['number'], unique=False)
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
