"""empty message

Revision ID: ebb164abd929
Revises: 4dda4c44e85b
Create Date: 2021-05-17 16:20:42.998749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebb164abd929'
down_revision = '4dda4c44e85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_number'), 'debit', ['number'], unique=False)
    op.add_column('address', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'member', ['member_id'], ['id'])
    op.drop_column('address', 'uid')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.add_column('address', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'member_id')
    op.drop_index(op.f('ix_debit_number'), table_name='debit')
    op.drop_table('debit')
    # ### end Alembic commands ###
